services:
  # Backend Service (Java Spring Boot)
  - type: web
    name: backend-service
    env: docker
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://db.dqbuppagnagzwdrtyemp.supabase.co:5432/postgres
      - key: DATABASE_USERNAME
        value: postgres
      - key: DATABASE_PASSWORD
        value: "[112131415161718191]" # Ensure you set the correct password securely
      - key: REDIS_URL
        value: redis://localhost:6379 # To be replaced with a real Redis connection
      - key: JWT_SECRET
        generateValue: true
