ALTER TABLE bookings DROP CONSTRAINT bookings_status_check;
ALTER TABLE bookings ADD CONSTRAINT bookings_status_check CHECK (status IN ('SEARCHING','ACCEPTED','ARRIVED','IN_PROGRESS','PAYMENT_PENDING','PAYMENT_CLAIMED','COMPLETED','CANCELLED_COMPENSATED','CANCELLED'));
